name: Generate TMX files for a release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Cache distfiles
        uses: actions/cache@v4
        with:
          path: distfiles
          key: ${{ runner.os }}-distfiles-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-distfiles-

      - name: Install tikal
        run: |
          mkdir -p distfiles
          wget -O distfiles/okapi.zip https://okapiframework.org/binaries/main/1.48.0/okapi-apps_gtk2-linux-x86_64_1.48.0.zip
          (cd bin && unzip ../distfiles/okapi.zip)
          mv bin/tikal.sh bin/tikal
          chmod +x bin/tikal

      - name: Generate TMX files
        run: |
          export PATH="`realpath bin`:${PATH}"
          echo "PATH: ${PATH}"
          FILES=`echo examples/*`
          echo "${FILES}"
          for F in ${FILES}; do
            echo "Generating TMX files for: ${F}"
            bundle exec exe/tmx-foss all "${F}" --log-level debug
          done

      - name: Archive artifacts per directory
        run: |
          mkdir packages
          tar -czf packages/all.tgz -C stage .
          (cd stage && zip -r packages/all.zip .)
          cd stage

          for dir in */; do
            dir_name="${dir%/}"

            echo "Packing artifacts for: ${dir_name}"
            tar -czf "../packages/${dir_name}.tgz" "$dir_name"
            zip -r "../packages/${dir_name}.zip" "$dir_name"
          done

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/*.tgz
            packages/*.zip
          generate_release_notes: true
